[rospy.client][INFO] 2020-07-02 13:14:18,107: init_node, name[/robot2/urdf_spawner], pid[12049]
[xmlrpc][INFO] 2020-07-02 13:14:18,111: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2020-07-02 13:14:18,111: ROS Slave URI: [http://177b797fd17c:45319/]
[xmlrpc][INFO] 2020-07-02 13:14:18,111: Started XML-RPC server [http://177b797fd17c:45319/]
[rospy.impl.masterslave][INFO] 2020-07-02 13:14:18,112: _ready: http://177b797fd17c:45319/
[rospy.registration][INFO] 2020-07-02 13:14:18,117: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-07-02 13:14:18,117: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-07-02 13:14:18,212: registered with master
[rospy.rosout][INFO] 2020-07-02 13:14:18,212: initializing /rosout core topic
[rospy.rosout][INFO] 2020-07-02 13:14:18,214: connected to core topic /rosout
[rospy.simtime][INFO] 2020-07-02 13:14:18,216: initializing /clock core topic
[rospy.simtime][INFO] 2020-07-02 13:14:18,228: connected to core topic /clock
[rospy.internal][INFO] 2020-07-02 13:14:18,239: topic[/clock] adding connection to [http://177b797fd17c:35485/], count 0
[rosout][INFO] 2020-07-02 13:14:18,248: Loading model XML from ros parameter
[rosout][INFO] 2020-07-02 13:14:18,255: Waiting for service /gazebo/spawn_urdf_model
[rosout][INFO] 2020-07-02 13:14:18,257: Calling service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2020-07-02 13:14:18,333: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2020-07-02 13:14:59,634: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-07-02 13:14:59,637: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-07-02 13:14:59,638: topic[/clock] removing connection to http://177b797fd17c:35485/
[rospy.internal][WARNING] 2020-07-02 13:14:59,639: Unknown error initiating TCP/IP socket to 177b797fd17c:34307 (http://177b797fd17c:35485/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2020-07-02 13:14:59,639: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2020-07-02 13:14:59,639: signal-2
[rospy.internal][ERROR] 2020-07-02 13:14:59,771: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 729, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 4] Interrupted system call

[rospy.core][INFO] 2020-07-02 13:14:59,773: signal_shutdown [atexit]
