[rospy.client][INFO] 2019-07-02 15:05:12,699: init_node, name[/mybot_spawn], pid[24824]
[xmlrpc][INFO] 2019-07-02 15:05:12,699: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-07-02 15:05:12,700: Started XML-RPC server [http://f6566a55c2b3:43555/]
[rospy.init][INFO] 2019-07-02 15:05:12,700: ROS Slave URI: [http://f6566a55c2b3:43555/]
[rospy.impl.masterslave][INFO] 2019-07-02 15:05:12,700: _ready: http://f6566a55c2b3:43555/
[xmlrpc][INFO] 2019-07-02 15:05:12,701: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-07-02 15:05:12,702: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-07-02 15:05:12,801: registered with master
[rospy.rosout][INFO] 2019-07-02 15:05:12,801: initializing /rosout core topic
[rospy.rosout][INFO] 2019-07-02 15:05:12,806: connected to core topic /rosout
[rospy.simtime][INFO] 2019-07-02 15:05:12,808: initializing /clock core topic
[rospy.simtime][INFO] 2019-07-02 15:05:12,811: connected to core topic /clock
[rosout][INFO] 2019-07-02 15:05:12,815: Loading model XML from ros parameter
[rosout][INFO] 2019-07-02 15:05:12,821: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2019-07-02 15:05:12,822: topic[/clock] adding connection to [http://f6566a55c2b3:41365/], count 0
[rosout][INFO] 2019-07-02 15:05:12,823: Calling service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2019-07-02 15:05:13,101: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2019-07-02 15:05:13,270: Spawn status: SpawnModel: Successfully spawned entity
[rospy.core][INFO] 2019-07-02 15:05:13,271: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-07-02 15:05:13,275: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-07-02 15:05:13,275: topic[/clock] removing connection to http://f6566a55c2b3:41365/
[rospy.topics][ERROR] 2019-07-02 15:05:13,276: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2019-07-02 15:05:13,276: atexit
[rospy.internal][WARNING] 2019-07-02 15:05:13,277: Unknown error initiating TCP/IP socket to f6566a55c2b3:60693 (http://f6566a55c2b3:41365/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

