[rospy.client][INFO] 2019-06-25 07:06:58,168: init_node, name[/teleop_twist_keyboard], pid[4483]
[xmlrpc][INFO] 2019-06-25 07:06:58,169: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 07:06:58,170: Started XML-RPC server [http://dc5b429f784e:40455/]
[rospy.init][INFO] 2019-06-25 07:06:58,171: ROS Slave URI: [http://dc5b429f784e:40455/]
[rospy.impl.masterslave][INFO] 2019-06-25 07:06:58,171: _ready: http://dc5b429f784e:40455/
[xmlrpc][INFO] 2019-06-25 07:06:58,173: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 07:06:58,173: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 07:06:58,174: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 07:06:58,272: registered with master
[rospy.rosout][INFO] 2019-06-25 07:06:58,272: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 07:06:58,289: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 07:06:58,293: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 07:06:58,297: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 07:06:58,344: topic[/clock] adding connection to [http://dc5b429f784e:43259/], count 0
[rospy.internal][INFO] 2019-06-25 07:06:58,445: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 07:06:58,495: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 07:07:39,952: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 07:07:39,960: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 07:07:39,962: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 07:07:39,964: topic[/clock] removing connection to http://dc5b429f784e:43259/
[rospy.impl.masterslave][INFO] 2019-06-25 07:07:39,964: atexit
[rospy.internal][WARNING] 2019-06-25 07:07:39,965: Unknown error initiating TCP/IP socket to dc5b429f784e:47571 (http://dc5b429f784e:43259/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.client][INFO] 2019-06-25 07:20:00,657: init_node, name[/teleop_twist_keyboard], pid[7041]
[xmlrpc][INFO] 2019-06-25 07:20:00,657: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 07:20:00,658: Started XML-RPC server [http://dc5b429f784e:34845/]
[rospy.init][INFO] 2019-06-25 07:20:00,658: ROS Slave URI: [http://dc5b429f784e:34845/]
[rospy.impl.masterslave][INFO] 2019-06-25 07:20:00,658: _ready: http://dc5b429f784e:34845/
[rospy.registration][INFO] 2019-06-25 07:20:00,659: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2019-06-25 07:20:00,659: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 07:20:00,659: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 07:20:00,759: registered with master
[rospy.rosout][INFO] 2019-06-25 07:20:00,759: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 07:20:00,761: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 07:20:00,762: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 07:20:00,765: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 07:20:00,777: topic[/clock] adding connection to [http://dc5b429f784e:34403/], count 0
[rospy.internal][INFO] 2019-06-25 07:20:00,879: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 07:20:00,972: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 07:20:02,023: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 07:20:02,027: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 07:20:02,028: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 07:20:02,028: topic[/clock] removing connection to http://dc5b429f784e:34403/
[rospy.impl.masterslave][INFO] 2019-06-25 07:20:02,028: atexit
[rospy.internal][ERROR] 2019-06-25 07:20:02,029: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 729, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.client][INFO] 2019-06-25 07:20:47,992: init_node, name[/teleop_twist_keyboard], pid[7440]
[xmlrpc][INFO] 2019-06-25 07:20:47,992: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 07:20:47,993: Started XML-RPC server [http://dc5b429f784e:41849/]
[rospy.init][INFO] 2019-06-25 07:20:47,993: ROS Slave URI: [http://dc5b429f784e:41849/]
[rospy.impl.masterslave][INFO] 2019-06-25 07:20:47,993: _ready: http://dc5b429f784e:41849/
[xmlrpc][INFO] 2019-06-25 07:20:47,994: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 07:20:47,995: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 07:20:47,995: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 07:20:48,093: registered with master
[rospy.rosout][INFO] 2019-06-25 07:20:48,094: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 07:20:48,096: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 07:20:48,097: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 07:20:48,100: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 07:20:48,116: topic[/clock] adding connection to [http://dc5b429f784e:46865/], count 0
[rospy.internal][INFO] 2019-06-25 07:20:48,223: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 07:20:48,327: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 07:22:11,912: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 07:22:11,922: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 07:22:11,922: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 07:22:11,923: topic[/clock] removing connection to http://dc5b429f784e:46865/
[rospy.impl.masterslave][INFO] 2019-06-25 07:22:11,924: atexit
[rospy.client][INFO] 2019-06-25 07:45:39,785: init_node, name[/teleop_twist_keyboard], pid[9823]
[xmlrpc][INFO] 2019-06-25 07:45:39,786: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2019-06-25 07:45:39,787: ROS Slave URI: [http://dc5b429f784e:37627/]
[xmlrpc][INFO] 2019-06-25 07:45:39,787: Started XML-RPC server [http://dc5b429f784e:37627/]
[rospy.impl.masterslave][INFO] 2019-06-25 07:45:39,788: _ready: http://dc5b429f784e:37627/
[xmlrpc][INFO] 2019-06-25 07:45:39,804: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 07:45:39,805: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 07:45:39,805: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 07:45:39,888: registered with master
[rospy.rosout][INFO] 2019-06-25 07:45:39,888: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 07:45:39,891: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 07:45:39,895: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 07:45:39,901: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 07:45:39,928: topic[/clock] adding connection to [http://dc5b429f784e:38061/], count 0
[rospy.internal][INFO] 2019-06-25 07:45:40,037: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 07:45:40,094: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 07:47:59,933: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 07:47:59,938: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 07:47:59,938: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 07:47:59,938: topic[/clock] removing connection to http://dc5b429f784e:38061/
[rospy.impl.masterslave][INFO] 2019-06-25 07:47:59,938: atexit
[rospy.client][INFO] 2019-06-25 08:09:50,534: init_node, name[/teleop_twist_keyboard], pid[14978]
[xmlrpc][INFO] 2019-06-25 08:09:50,535: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 08:09:50,535: Started XML-RPC server [http://dc5b429f784e:37813/]
[rospy.impl.masterslave][INFO] 2019-06-25 08:09:50,535: _ready: http://dc5b429f784e:37813/
[rospy.init][INFO] 2019-06-25 08:09:50,536: ROS Slave URI: [http://dc5b429f784e:37813/]
[xmlrpc][INFO] 2019-06-25 08:09:50,537: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 08:09:50,537: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 08:09:50,538: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 08:09:50,637: registered with master
[rospy.rosout][INFO] 2019-06-25 08:09:50,637: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 08:09:50,639: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 08:09:50,641: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 08:09:50,645: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 08:09:50,658: topic[/clock] adding connection to [http://dc5b429f784e:46377/], count 0
[rospy.internal][INFO] 2019-06-25 08:09:50,761: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 08:09:50,852: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 08:15:00,081: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 08:15:00,084: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 08:15:00,085: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 08:15:00,085: topic[/clock] removing connection to http://dc5b429f784e:46377/
[rospy.impl.masterslave][INFO] 2019-06-25 08:15:00,085: atexit
[rospy.client][INFO] 2019-06-25 12:21:35,259: init_node, name[/teleop_twist_keyboard], pid[55098]
[xmlrpc][INFO] 2019-06-25 12:21:35,259: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 12:21:35,260: Started XML-RPC server [http://dc5b429f784e:41237/]
[rospy.impl.masterslave][INFO] 2019-06-25 12:21:35,260: _ready: http://dc5b429f784e:41237/
[rospy.init][INFO] 2019-06-25 12:21:35,261: ROS Slave URI: [http://dc5b429f784e:41237/]
[xmlrpc][INFO] 2019-06-25 12:21:35,261: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 12:21:35,263: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 12:21:35,264: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 12:21:35,362: registered with master
[rospy.rosout][INFO] 2019-06-25 12:21:35,362: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 12:21:35,367: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 12:21:35,372: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 12:21:35,377: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 12:21:35,386: topic[/clock] adding connection to [http://dc5b429f784e:42391/], count 0
[rospy.internal][INFO] 2019-06-25 12:21:35,590: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 12:21:35,645: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 12:22:10,231: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 12:22:10,245: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 12:22:10,245: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 12:22:10,245: topic[/clock] removing connection to http://dc5b429f784e:42391/
[rospy.impl.masterslave][INFO] 2019-06-25 12:22:10,246: atexit
[rospy.client][INFO] 2019-06-25 12:26:09,148: init_node, name[/teleop_twist_keyboard], pid[56241]
[xmlrpc][INFO] 2019-06-25 12:26:09,149: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 12:26:09,151: Started XML-RPC server [http://dc5b429f784e:40789/]
[rospy.init][INFO] 2019-06-25 12:26:09,151: ROS Slave URI: [http://dc5b429f784e:40789/]
[rospy.impl.masterslave][INFO] 2019-06-25 12:26:09,151: _ready: http://dc5b429f784e:40789/
[xmlrpc][INFO] 2019-06-25 12:26:09,152: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 12:26:09,154: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 12:26:09,154: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 12:26:09,252: registered with master
[rospy.rosout][INFO] 2019-06-25 12:26:09,252: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 12:26:09,256: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 12:26:09,258: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 12:26:09,264: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 12:26:09,280: topic[/clock] adding connection to [http://dc5b429f784e:44643/], count 0
[rospy.internal][INFO] 2019-06-25 12:26:09,439: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 12:26:09,506: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 12:26:55,565: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 12:26:55,571: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 12:26:55,571: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 12:26:55,572: topic[/clock] removing connection to http://dc5b429f784e:44643/
[rospy.impl.masterslave][INFO] 2019-06-25 12:26:55,572: atexit
[rospy.client][INFO] 2019-06-25 12:52:22,759: init_node, name[/teleop_twist_keyboard], pid[61789]
[xmlrpc][INFO] 2019-06-25 12:52:22,760: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 12:52:22,761: Started XML-RPC server [http://dc5b429f784e:42723/]
[rospy.impl.masterslave][INFO] 2019-06-25 12:52:22,761: _ready: http://dc5b429f784e:42723/
[rospy.init][INFO] 2019-06-25 12:52:22,761: ROS Slave URI: [http://dc5b429f784e:42723/]
[xmlrpc][INFO] 2019-06-25 12:52:22,763: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 12:52:22,764: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 12:52:22,765: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 12:52:22,863: registered with master
[rospy.rosout][INFO] 2019-06-25 12:52:22,863: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 12:52:22,866: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 12:52:22,873: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 12:52:22,882: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 12:52:22,900: topic[/clock] adding connection to [http://dc5b429f784e:42149/], count 0
[rospy.internal][INFO] 2019-06-25 12:52:23,074: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 12:52:23,091: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 12:52:36,564: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 12:52:36,571: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 12:52:36,572: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 12:52:36,573: topic[/clock] removing connection to http://dc5b429f784e:42149/
[rospy.impl.masterslave][INFO] 2019-06-25 12:52:36,573: atexit
[rospy.core][INFO] 2019-06-25 12:52:36,656: signal_shutdown [signal-2]
[rospy.core][INFO] 2019-06-25 12:52:36,796: signal_shutdown [signal-2]
[rospy.core][INFO] 2019-06-25 12:52:36,938: signal_shutdown [signal-2]
[rospy.core][INFO] 2019-06-25 12:52:37,082: signal_shutdown [signal-2]
[rospy.client][INFO] 2019-06-25 12:54:52,208: init_node, name[/teleop_twist_keyboard], pid[62020]
[xmlrpc][INFO] 2019-06-25 12:54:52,209: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 12:54:52,210: Started XML-RPC server [http://dc5b429f784e:37881/]
[rospy.impl.masterslave][INFO] 2019-06-25 12:54:52,210: _ready: http://dc5b429f784e:37881/
[rospy.init][INFO] 2019-06-25 12:54:52,211: ROS Slave URI: [http://dc5b429f784e:37881/]
[xmlrpc][INFO] 2019-06-25 12:54:52,212: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 12:54:52,213: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 12:54:52,213: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 12:54:52,312: registered with master
[rospy.rosout][INFO] 2019-06-25 12:54:52,312: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 12:54:52,316: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 12:54:52,318: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 12:54:52,324: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 12:54:52,336: topic[/clock] adding connection to [http://dc5b429f784e:42149/], count 0
[rospy.internal][INFO] 2019-06-25 12:54:52,439: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 12:54:52,545: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 12:54:59,859: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 12:54:59,865: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 12:54:59,866: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 12:54:59,866: topic[/clock] removing connection to http://dc5b429f784e:42149/
[rospy.impl.masterslave][INFO] 2019-06-25 12:54:59,866: atexit
[rospy.client][INFO] 2019-06-25 12:56:12,035: init_node, name[/teleop_twist_keyboard], pid[62676]
[xmlrpc][INFO] 2019-06-25 12:56:12,036: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 12:56:12,036: Started XML-RPC server [http://dc5b429f784e:38403/]
[rospy.impl.masterslave][INFO] 2019-06-25 12:56:12,037: _ready: http://dc5b429f784e:38403/
[rospy.init][INFO] 2019-06-25 12:56:12,037: ROS Slave URI: [http://dc5b429f784e:38403/]
[xmlrpc][INFO] 2019-06-25 12:56:12,038: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 12:56:12,039: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 12:56:12,039: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 12:56:12,138: registered with master
[rospy.rosout][INFO] 2019-06-25 12:56:12,139: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 12:56:12,142: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 12:56:12,145: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 12:56:12,151: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 12:56:12,161: topic[/clock] adding connection to [http://dc5b429f784e:46009/], count 0
[rospy.internal][INFO] 2019-06-25 12:56:12,263: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 12:56:12,413: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2019-06-25 12:58:09,001: Unable to initiate TCP/IP socket to dc5b429f784e:45529 (http://dc5b429f784e:46009/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 45529 to [172.17.0.2:34118 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 12:58:10,004: Unable to initiate TCP/IP socket to dc5b429f784e:45529 (http://dc5b429f784e:46009/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 45529 to [172.17.0.2:34188 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 12:58:12,007: Unable to initiate TCP/IP socket to dc5b429f784e:45529 (http://dc5b429f784e:46009/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 45529 to [172.17.0.2:34190 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 12:58:16,009: Unable to initiate TCP/IP socket to dc5b429f784e:45529 (http://dc5b429f784e:46009/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 45529 to [172.17.0.2:34192 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][WARNING] 2019-06-25 12:58:24,011: Unknown error initiating TCP/IP socket to dc5b429f784e:45529 (http://dc5b429f784e:46009/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 12:58:24,012: topic[/clock] removing connection to http://dc5b429f784e:46009/
[rospy.internal][INFO] 2019-06-25 12:58:24,271: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 12:58:28,039: topic[/clock] adding connection to [http://dc5b429f784e:38027/], count 0
[rospy.internal][INFO] 2019-06-25 12:58:29,025: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.core][INFO] 2019-06-25 12:58:32,032: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 12:58:32,037: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 12:58:32,037: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 12:58:32,038: topic[/clock] removing connection to http://dc5b429f784e:38027/
[rospy.impl.masterslave][INFO] 2019-06-25 12:58:32,038: atexit
[rospy.client][INFO] 2019-06-25 12:59:36,485: init_node, name[/teleop_twist_keyboard], pid[63713]
[xmlrpc][INFO] 2019-06-25 12:59:36,486: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 12:59:36,487: Started XML-RPC server [http://dc5b429f784e:38485/]
[rospy.impl.masterslave][INFO] 2019-06-25 12:59:36,488: _ready: http://dc5b429f784e:38485/
[rospy.init][INFO] 2019-06-25 12:59:36,488: ROS Slave URI: [http://dc5b429f784e:38485/]
[xmlrpc][INFO] 2019-06-25 12:59:36,489: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 12:59:36,491: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 12:59:36,492: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 12:59:36,590: registered with master
[rospy.rosout][INFO] 2019-06-25 12:59:36,590: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 12:59:36,593: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 12:59:36,595: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 12:59:36,601: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 12:59:36,616: topic[/clock] adding connection to [http://dc5b429f784e:38027/], count 0
[rospy.internal][INFO] 2019-06-25 12:59:36,728: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 12:59:36,861: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 13:01:28,281: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 13:01:28,286: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 13:01:28,287: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 13:01:28,287: topic[/clock] removing connection to http://dc5b429f784e:38027/
[rospy.impl.masterslave][INFO] 2019-06-25 13:01:28,288: atexit
[rospy.client][INFO] 2019-06-25 13:15:06,281: init_node, name[/teleop_twist_keyboard], pid[67385]
[xmlrpc][INFO] 2019-06-25 13:15:06,282: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 13:15:06,283: Started XML-RPC server [http://dc5b429f784e:37951/]
[rospy.init][INFO] 2019-06-25 13:15:06,284: ROS Slave URI: [http://dc5b429f784e:37951/]
[rospy.impl.masterslave][INFO] 2019-06-25 13:15:06,284: _ready: http://dc5b429f784e:37951/
[xmlrpc][INFO] 2019-06-25 13:15:06,285: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 13:15:06,286: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 13:15:06,286: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 13:15:06,384: registered with master
[rospy.rosout][INFO] 2019-06-25 13:15:06,385: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 13:15:06,387: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 13:15:06,389: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 13:15:06,396: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 13:15:06,414: topic[/clock] adding connection to [http://dc5b429f784e:43543/], count 0
[rospy.internal][INFO] 2019-06-25 13:15:06,520: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 13:15:06,626: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2019-06-25 13:16:48,130: Unable to initiate TCP/IP socket to dc5b429f784e:50065 (http://dc5b429f784e:43543/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 50065 to [172.17.0.2:43098 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 13:16:49,132: Unable to initiate TCP/IP socket to dc5b429f784e:50065 (http://dc5b429f784e:43543/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 50065 to [172.17.0.2:43182 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 13:16:51,135: Unable to initiate TCP/IP socket to dc5b429f784e:50065 (http://dc5b429f784e:43543/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 50065 to [172.17.0.2:43194 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 13:16:55,137: Unable to initiate TCP/IP socket to dc5b429f784e:50065 (http://dc5b429f784e:43543/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 50065 to [172.17.0.2:43206 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 13:17:03,142: Unable to initiate TCP/IP socket to dc5b429f784e:50065 (http://dc5b429f784e:43543/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 50065 to [172.17.0.2:43208 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][INFO] 2019-06-25 13:17:12,994: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2019-06-25 13:17:19,152: Unable to initiate TCP/IP socket to dc5b429f784e:50065 (http://dc5b429f784e:43543/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 50065 to [172.17.0.2:43244 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][INFO] 2019-06-25 13:17:26,503: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][WARNING] 2019-06-25 13:17:51,183: Unknown error initiating TCP/IP socket to dc5b429f784e:50065 (http://dc5b429f784e:43543/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 13:17:51,184: topic[/clock] removing connection to http://dc5b429f784e:43543/
[rospy.core][INFO] 2019-06-25 13:18:47,038: signal_shutdown [atexit]
[rospy.impl.masterslave][INFO] 2019-06-25 13:18:47,045: atexit
[rospy.client][INFO] 2019-06-25 13:33:12,475: init_node, name[/teleop_twist_keyboard], pid[72745]
[xmlrpc][INFO] 2019-06-25 13:33:12,477: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 13:33:12,478: Started XML-RPC server [http://dc5b429f784e:33349/]
[rospy.init][INFO] 2019-06-25 13:33:12,478: ROS Slave URI: [http://dc5b429f784e:33349/]
[rospy.impl.masterslave][INFO] 2019-06-25 13:33:12,479: _ready: http://dc5b429f784e:33349/
[xmlrpc][INFO] 2019-06-25 13:33:12,479: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 13:33:12,480: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 13:33:12,480: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 13:33:12,579: registered with master
[rospy.rosout][INFO] 2019-06-25 13:33:12,579: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 13:33:12,586: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 13:33:12,589: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 13:33:12,595: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 13:33:12,610: topic[/clock] adding connection to [http://dc5b429f784e:39511/], count 0
[rospy.internal][INFO] 2019-06-25 13:33:12,712: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 13:33:12,807: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 13:34:12,560: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 13:34:12,571: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 13:34:12,572: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 13:34:12,573: topic[/clock] removing connection to http://dc5b429f784e:39511/
[rospy.internal][ERROR] 2019-06-25 13:34:12,573: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 729, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.impl.masterslave][INFO] 2019-06-25 13:34:12,574: atexit
[rospy.core][INFO] 2019-06-25 13:34:12,732: signal_shutdown [signal-2]
[rospy.client][INFO] 2019-06-25 14:16:22,373: init_node, name[/teleop_twist_keyboard], pid[83159]
[xmlrpc][INFO] 2019-06-25 14:16:22,374: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 14:16:22,375: Started XML-RPC server [http://dc5b429f784e:46423/]
[rospy.impl.masterslave][INFO] 2019-06-25 14:16:22,375: _ready: http://dc5b429f784e:46423/
[rospy.init][INFO] 2019-06-25 14:16:22,375: ROS Slave URI: [http://dc5b429f784e:46423/]
[xmlrpc][INFO] 2019-06-25 14:16:22,377: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 14:16:22,378: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 14:16:22,378: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 14:16:22,476: registered with master
[rospy.rosout][INFO] 2019-06-25 14:16:22,477: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 14:16:22,484: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 14:16:22,487: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 14:16:22,502: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 14:16:22,552: topic[/clock] adding connection to [http://dc5b429f784e:46565/], count 0
[rospy.internal][INFO] 2019-06-25 14:16:22,636: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-06-25 14:16:22,658: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.core][INFO] 2019-06-25 14:19:10,042: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 14:19:10,065: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 14:19:10,066: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 14:19:10,067: topic[/clock] removing connection to http://dc5b429f784e:46565/
[rospy.impl.masterslave][INFO] 2019-06-25 14:19:10,067: atexit
[rospy.client][INFO] 2019-06-25 14:20:46,090: init_node, name[/teleop_twist_keyboard], pid[84112]
[xmlrpc][INFO] 2019-06-25 14:20:46,118: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 14:20:46,118: Started XML-RPC server [http://dc5b429f784e:40511/]
[rospy.impl.masterslave][INFO] 2019-06-25 14:20:46,119: _ready: http://dc5b429f784e:40511/
[rospy.init][INFO] 2019-06-25 14:20:46,119: ROS Slave URI: [http://dc5b429f784e:40511/]
[rospy.registration][INFO] 2019-06-25 14:20:46,124: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 14:20:46,124: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[xmlrpc][INFO] 2019-06-25 14:20:46,125: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2019-06-25 14:20:46,220: registered with master
[rospy.rosout][INFO] 2019-06-25 14:20:46,220: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 14:20:46,222: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 14:20:46,226: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 14:20:46,233: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 14:20:46,245: topic[/clock] adding connection to [http://dc5b429f784e:37337/], count 0
[rospy.internal][INFO] 2019-06-25 14:20:46,365: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 14:20:46,428: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 14:22:04,681: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 14:22:04,696: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 14:22:04,696: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 14:22:04,697: topic[/clock] removing connection to http://dc5b429f784e:37337/
[rospy.impl.masterslave][INFO] 2019-06-25 14:22:04,697: atexit
[rospy.client][INFO] 2019-06-25 14:23:56,421: init_node, name[/teleop_twist_keyboard], pid[85032]
[xmlrpc][INFO] 2019-06-25 14:23:56,421: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 14:23:56,430: Started XML-RPC server [http://dc5b429f784e:39565/]
[rospy.impl.masterslave][INFO] 2019-06-25 14:23:56,430: _ready: http://dc5b429f784e:39565/
[rospy.init][INFO] 2019-06-25 14:23:56,430: ROS Slave URI: [http://dc5b429f784e:39565/]
[rospy.registration][INFO] 2019-06-25 14:23:56,435: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 14:23:56,435: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[xmlrpc][INFO] 2019-06-25 14:23:56,436: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2019-06-25 14:23:56,531: registered with master
[rospy.rosout][INFO] 2019-06-25 14:23:56,531: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 14:23:56,544: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 14:23:56,547: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 14:23:56,556: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 14:23:56,623: topic[/clock] adding connection to [http://dc5b429f784e:34801/], count 0
[rospy.internal][INFO] 2019-06-25 14:23:56,725: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 14:23:56,794: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2019-06-25 14:25:11,387: Unable to initiate TCP/IP socket to dc5b429f784e:53481 (http://dc5b429f784e:34801/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 53481 to [172.17.0.2:54924 on socket 15]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:25:12,388: Unable to initiate TCP/IP socket to dc5b429f784e:53481 (http://dc5b429f784e:34801/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 53481 to [172.17.0.2:54996 on socket 15]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:25:14,391: Unable to initiate TCP/IP socket to dc5b429f784e:53481 (http://dc5b429f784e:34801/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 53481 to [172.17.0.2:55032 on socket 15]] [/teleop_twist_keyboard].

[rospy.core][INFO] 2019-06-25 14:25:15,738: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 14:25:15,742: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 14:25:15,742: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 14:25:15,742: topic[/clock] removing connection to http://dc5b429f784e:34801/
[rospy.impl.masterslave][INFO] 2019-06-25 14:25:15,742: atexit
[rospy.client][INFO] 2019-06-25 14:27:51,683: init_node, name[/teleop_twist_keyboard], pid[86643]
[xmlrpc][INFO] 2019-06-25 14:27:51,683: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 14:27:51,684: Started XML-RPC server [http://dc5b429f784e:45897/]
[rospy.impl.masterslave][INFO] 2019-06-25 14:27:51,684: _ready: http://dc5b429f784e:45897/
[rospy.init][INFO] 2019-06-25 14:27:51,684: ROS Slave URI: [http://dc5b429f784e:45897/]
[rospy.registration][INFO] 2019-06-25 14:27:51,686: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 14:27:51,686: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[xmlrpc][INFO] 2019-06-25 14:27:51,685: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2019-06-25 14:27:51,785: registered with master
[rospy.rosout][INFO] 2019-06-25 14:27:51,786: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 14:27:51,788: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 14:27:51,791: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 14:27:51,795: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 14:27:51,817: topic[/clock] adding connection to [http://dc5b429f784e:34133/], count 0
[rospy.internal][INFO] 2019-06-25 14:27:51,914: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 14:27:52,040: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2019-06-25 14:31:10,353: Unable to initiate TCP/IP socket to dc5b429f784e:41093 (http://dc5b429f784e:34133/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 41093 to [172.17.0.2:45880 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:31:11,355: Unable to initiate TCP/IP socket to dc5b429f784e:41093 (http://dc5b429f784e:34133/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 41093 to [172.17.0.2:45958 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:31:13,358: Unable to initiate TCP/IP socket to dc5b429f784e:41093 (http://dc5b429f784e:34133/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 41093 to [172.17.0.2:45986 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:31:17,363: Unable to initiate TCP/IP socket to dc5b429f784e:41093 (http://dc5b429f784e:34133/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 41093 to [172.17.0.2:45988 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][WARNING] 2019-06-25 14:31:25,365: Unknown error initiating TCP/IP socket to dc5b429f784e:41093 (http://dc5b429f784e:34133/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 14:31:25,365: topic[/clock] removing connection to http://dc5b429f784e:34133/
[rospy.internal][INFO] 2019-06-25 14:31:25,461: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 14:31:30,128: topic[/clock] adding connection to [http://dc5b429f784e:41275/], count 0
[rospy.internal][INFO] 2019-06-25 14:31:31,225: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][ERROR] 2019-06-25 14:36:03,123: Unable to initiate TCP/IP socket to dc5b429f784e:57523 (http://dc5b429f784e:41275/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 57523 to [172.17.0.2:55020 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:36:04,125: Unable to initiate TCP/IP socket to dc5b429f784e:57523 (http://dc5b429f784e:41275/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 57523 to [172.17.0.2:55090 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:36:06,127: Unable to initiate TCP/IP socket to dc5b429f784e:57523 (http://dc5b429f784e:41275/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 57523 to [172.17.0.2:55128 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:36:10,129: Unable to initiate TCP/IP socket to dc5b429f784e:57523 (http://dc5b429f784e:41275/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 57523 to [172.17.0.2:55132 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:36:18,139: Unable to initiate TCP/IP socket to dc5b429f784e:57523 (http://dc5b429f784e:41275/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 57523 to [172.17.0.2:55190 on socket 18]] [/teleop_twist_keyboard].

[rospy.internal][INFO] 2019-06-25 14:36:19,838: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 14:36:23,755: topic[/clock] adding connection to [http://dc5b429f784e:45593/], count 1
[rospy.internal][INFO] 2019-06-25 14:36:24,870: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][WARNING] 2019-06-25 14:36:34,150: Unknown error initiating TCP/IP socket to dc5b429f784e:57523 (http://dc5b429f784e:41275/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 14:36:34,150: topic[/clock] removing connection to http://dc5b429f784e:41275/
[rospy.core][INFO] 2019-06-25 14:38:06,110: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 14:38:06,125: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 14:38:06,125: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 14:38:06,126: topic[/clock] removing connection to http://dc5b429f784e:45593/
[rospy.impl.masterslave][INFO] 2019-06-25 14:38:06,126: atexit
[rospy.client][INFO] 2019-06-25 14:38:10,238: init_node, name[/teleop_twist_keyboard], pid[88895]
[xmlrpc][INFO] 2019-06-25 14:38:10,261: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 14:38:10,262: Started XML-RPC server [http://dc5b429f784e:37283/]
[rospy.impl.masterslave][INFO] 2019-06-25 14:38:10,262: _ready: http://dc5b429f784e:37283/
[rospy.init][INFO] 2019-06-25 14:38:10,262: ROS Slave URI: [http://dc5b429f784e:37283/]
[xmlrpc][INFO] 2019-06-25 14:38:10,265: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 14:38:10,265: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 14:38:10,266: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 14:38:10,363: registered with master
[rospy.rosout][INFO] 2019-06-25 14:38:10,364: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 14:38:10,374: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 14:38:10,379: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 14:38:10,414: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 14:38:10,441: topic[/clock] adding connection to [http://dc5b429f784e:45593/], count 0
[rospy.internal][INFO] 2019-06-25 14:38:10,551: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 14:38:10,617: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2019-06-25 14:43:21,501: Unable to initiate TCP/IP socket to dc5b429f784e:44027 (http://dc5b429f784e:45593/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 44027 to [172.17.0.2:35656 on socket 20]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:43:22,504: Unable to initiate TCP/IP socket to dc5b429f784e:44027 (http://dc5b429f784e:45593/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 44027 to [172.17.0.2:35726 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:43:24,505: Unable to initiate TCP/IP socket to dc5b429f784e:44027 (http://dc5b429f784e:45593/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 44027 to [172.17.0.2:35752 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:43:28,508: Unable to initiate TCP/IP socket to dc5b429f784e:44027 (http://dc5b429f784e:45593/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 44027 to [172.17.0.2:35758 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:43:36,511: Unable to initiate TCP/IP socket to dc5b429f784e:44027 (http://dc5b429f784e:45593/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 44027 to [172.17.0.2:35804 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][INFO] 2019-06-25 14:43:37,678: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 14:43:40,795: topic[/clock] adding connection to [http://dc5b429f784e:46243/], count 1
[rospy.internal][INFO] 2019-06-25 14:43:41,625: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][WARNING] 2019-06-25 14:43:52,528: Unknown error initiating TCP/IP socket to dc5b429f784e:44027 (http://dc5b429f784e:45593/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 14:43:52,530: topic[/clock] removing connection to http://dc5b429f784e:45593/
[rospy.internal][ERROR] 2019-06-25 14:47:34,857: Unable to initiate TCP/IP socket to dc5b429f784e:41441 (http://dc5b429f784e:46243/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 41441 to [172.17.0.2:38540 on socket 18]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:47:35,859: Unable to initiate TCP/IP socket to dc5b429f784e:41441 (http://dc5b429f784e:46243/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 41441 to [172.17.0.2:38610 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:47:37,861: Unable to initiate TCP/IP socket to dc5b429f784e:41441 (http://dc5b429f784e:46243/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 41441 to [172.17.0.2:38654 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:47:41,867: Unable to initiate TCP/IP socket to dc5b429f784e:41441 (http://dc5b429f784e:46243/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 41441 to [172.17.0.2:38656 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][INFO] 2019-06-25 14:47:47,479: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][WARNING] 2019-06-25 14:47:49,871: Unknown error initiating TCP/IP socket to dc5b429f784e:41441 (http://dc5b429f784e:46243/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 14:47:49,871: topic[/clock] removing connection to http://dc5b429f784e:46243/
[rospy.internal][INFO] 2019-06-25 14:47:50,500: topic[/clock] adding connection to [http://dc5b429f784e:37297/], count 0
[rospy.internal][ERROR] 2019-06-25 14:47:51,188: Unable to initiate TCP/IP socket to dc5b429f784e:52767 (http://dc5b429f784e:37297/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 52767 to [172.17.0.2:50784 on socket 9]] [/teleop_twist_keyboard].

[rospy.internal][WARNING] 2019-06-25 14:47:52,190: Unknown error initiating TCP/IP socket to dc5b429f784e:52767 (http://dc5b429f784e:37297/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 14:47:52,190: topic[/clock] removing connection to http://dc5b429f784e:37297/
[rospy.client][INFO] 2019-06-25 14:56:36,533: init_node, name[/teleop_twist_keyboard], pid[93102]
[xmlrpc][INFO] 2019-06-25 14:56:36,535: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 14:56:36,538: Started XML-RPC server [http://dc5b429f784e:38141/]
[rospy.init][INFO] 2019-06-25 14:56:36,539: ROS Slave URI: [http://dc5b429f784e:38141/]
[rospy.impl.masterslave][INFO] 2019-06-25 14:56:36,539: _ready: http://dc5b429f784e:38141/
[xmlrpc][INFO] 2019-06-25 14:56:36,541: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 14:56:36,542: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 14:56:36,543: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 14:56:36,640: registered with master
[rospy.rosout][INFO] 2019-06-25 14:56:36,640: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 14:56:36,654: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 14:56:36,673: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 14:56:36,696: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 14:56:36,723: topic[/clock] adding connection to [http://dc5b429f784e:33363/], count 0
[rospy.internal][INFO] 2019-06-25 14:56:36,891: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 14:56:36,920: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2019-06-25 14:57:51,523: Unable to initiate TCP/IP socket to dc5b429f784e:35027 (http://dc5b429f784e:33363/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 35027 to [172.17.0.2:57394 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 14:57:52,525: Unable to initiate TCP/IP socket to dc5b429f784e:35027 (http://dc5b429f784e:33363/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 35027 to [172.17.0.2:57462 on socket 16]] [/teleop_twist_keyboard].

[rospy.core][INFO] 2019-06-25 14:57:53,450: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 14:57:53,454: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 14:57:53,455: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 14:57:53,455: topic[/clock] removing connection to http://dc5b429f784e:33363/
[rospy.impl.masterslave][INFO] 2019-06-25 14:57:53,455: atexit
[rospy.client][INFO] 2019-06-25 20:52:12,669: init_node, name[/teleop_twist_keyboard], pid[2981]
[xmlrpc][INFO] 2019-06-25 20:52:12,676: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 20:52:12,678: Started XML-RPC server [http://dc5b429f784e:38899/]
[rospy.init][INFO] 2019-06-25 20:52:12,678: ROS Slave URI: [http://dc5b429f784e:38899/]
[rospy.impl.masterslave][INFO] 2019-06-25 20:52:12,678: _ready: http://dc5b429f784e:38899/
[xmlrpc][INFO] 2019-06-25 20:52:12,679: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 20:52:12,680: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 20:52:12,680: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 20:52:12,779: registered with master
[rospy.rosout][INFO] 2019-06-25 20:52:12,779: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 20:52:12,782: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 20:52:12,785: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 20:52:12,790: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 20:52:12,805: topic[/clock] adding connection to [http://dc5b429f784e:46213/], count 0
[rospy.internal][INFO] 2019-06-25 20:52:12,908: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 20:52:13,002: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2019-06-25 20:53:37,555: Unable to initiate TCP/IP socket to dc5b429f784e:34285 (http://dc5b429f784e:46213/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 34285 to [172.17.0.2:57764 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 20:53:38,557: Unable to initiate TCP/IP socket to dc5b429f784e:34285 (http://dc5b429f784e:46213/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 34285 to [172.17.0.2:57870 on socket 16]] [/teleop_twist_keyboard].

[rospy.core][INFO] 2019-06-25 20:53:38,942: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 20:53:38,945: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 20:53:38,945: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 20:53:38,946: topic[/clock] removing connection to http://dc5b429f784e:46213/
[rospy.impl.masterslave][INFO] 2019-06-25 20:53:38,946: atexit
[rospy.client][INFO] 2019-06-25 21:08:59,835: init_node, name[/teleop_twist_keyboard], pid[6284]
[xmlrpc][INFO] 2019-06-25 21:08:59,843: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 21:08:59,853: Started XML-RPC server [http://dc5b429f784e:40219/]
[rospy.init][INFO] 2019-06-25 21:08:59,854: ROS Slave URI: [http://dc5b429f784e:40219/]
[rospy.impl.masterslave][INFO] 2019-06-25 21:08:59,854: _ready: http://dc5b429f784e:40219/
[xmlrpc][INFO] 2019-06-25 21:08:59,873: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 21:08:59,874: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 21:08:59,874: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 21:08:59,954: registered with master
[rospy.rosout][INFO] 2019-06-25 21:08:59,955: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 21:08:59,965: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 21:08:59,971: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 21:08:59,981: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 21:09:00,016: topic[/clock] adding connection to [http://dc5b429f784e:35661/], count 0
[rospy.internal][INFO] 2019-06-25 21:09:00,121: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 21:09:00,273: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2019-06-25 21:17:57,239: Unable to initiate TCP/IP socket to dc5b429f784e:57603 (http://dc5b429f784e:35661/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 57603 to [172.17.0.2:33226 on socket 18]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 21:17:58,241: Unable to initiate TCP/IP socket to dc5b429f784e:57603 (http://dc5b429f784e:35661/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 57603 to [172.17.0.2:33330 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 21:18:00,244: Unable to initiate TCP/IP socket to dc5b429f784e:57603 (http://dc5b429f784e:35661/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 57603 to [172.17.0.2:33364 on socket 16]] [/teleop_twist_keyboard].

[rospy.core][INFO] 2019-06-25 21:18:00,441: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 21:18:00,445: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 21:18:00,445: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 21:18:00,445: topic[/clock] removing connection to http://dc5b429f784e:35661/
[rospy.impl.masterslave][INFO] 2019-06-25 21:18:00,445: atexit
[rospy.client][INFO] 2019-06-25 21:29:11,179: init_node, name[/teleop_twist_keyboard], pid[11524]
[xmlrpc][INFO] 2019-06-25 21:29:11,183: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 21:29:11,184: Started XML-RPC server [http://dc5b429f784e:45219/]
[rospy.impl.masterslave][INFO] 2019-06-25 21:29:11,184: _ready: http://dc5b429f784e:45219/
[rospy.init][INFO] 2019-06-25 21:29:11,185: ROS Slave URI: [http://dc5b429f784e:45219/]
[xmlrpc][INFO] 2019-06-25 21:29:11,186: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 21:29:11,187: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 21:29:11,187: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 21:29:11,286: registered with master
[rospy.rosout][INFO] 2019-06-25 21:29:11,289: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 21:29:11,293: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 21:29:11,300: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 21:29:11,324: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 21:29:11,378: topic[/clock] adding connection to [http://dc5b429f784e:39015/], count 0
[rospy.internal][INFO] 2019-06-25 21:29:11,483: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 21:29:11,573: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 21:51:39,177: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 21:51:39,184: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 21:51:39,185: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 21:51:39,185: topic[/clock] removing connection to http://dc5b429f784e:39015/
[rospy.impl.masterslave][INFO] 2019-06-25 21:51:39,186: atexit
[rospy.client][INFO] 2019-06-25 21:54:25,287: init_node, name[/teleop_twist_keyboard], pid[17435]
[xmlrpc][INFO] 2019-06-25 21:54:25,287: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 21:54:25,288: Started XML-RPC server [http://dc5b429f784e:41107/]
[rospy.init][INFO] 2019-06-25 21:54:25,289: ROS Slave URI: [http://dc5b429f784e:41107/]
[rospy.impl.masterslave][INFO] 2019-06-25 21:54:25,289: _ready: http://dc5b429f784e:41107/
[xmlrpc][INFO] 2019-06-25 21:54:25,291: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 21:54:25,291: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 21:54:25,292: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 21:54:25,390: registered with master
[rospy.rosout][INFO] 2019-06-25 21:54:25,391: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 21:54:25,393: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 21:54:25,396: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 21:54:25,401: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 21:54:25,416: topic[/clock] adding connection to [http://dc5b429f784e:34901/], count 0
[rospy.internal][INFO] 2019-06-25 21:54:25,518: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 21:54:25,524: topic[/rosout] adding connection to [/rosout], count 0
[rospy.client][INFO] 2019-06-25 22:14:33,138: init_node, name[/teleop_twist_keyboard], pid[24042]
[xmlrpc][INFO] 2019-06-25 22:14:33,139: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 22:14:33,140: Started XML-RPC server [http://dc5b429f784e:33733/]
[rospy.init][INFO] 2019-06-25 22:14:33,141: ROS Slave URI: [http://dc5b429f784e:33733/]
[rospy.impl.masterslave][INFO] 2019-06-25 22:14:33,142: _ready: http://dc5b429f784e:33733/
[xmlrpc][INFO] 2019-06-25 22:14:33,143: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 22:14:33,145: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 22:14:33,145: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 22:14:33,243: registered with master
[rospy.rosout][INFO] 2019-06-25 22:14:33,245: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 22:14:33,251: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 22:14:33,253: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 22:14:33,261: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 22:14:33,280: topic[/clock] adding connection to [http://dc5b429f784e:43879/], count 0
[rospy.internal][INFO] 2019-06-25 22:14:33,382: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 22:14:33,518: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 22:15:19,751: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 22:15:19,762: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 22:15:19,764: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 22:15:19,765: topic[/clock] removing connection to http://dc5b429f784e:43879/
[rospy.impl.masterslave][INFO] 2019-06-25 22:15:19,766: atexit
[rospy.client][INFO] 2019-06-25 22:17:54,124: init_node, name[/teleop_twist_keyboard], pid[25450]
[xmlrpc][INFO] 2019-06-25 22:17:54,127: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 22:17:54,128: Started XML-RPC server [http://dc5b429f784e:41539/]
[rospy.impl.masterslave][INFO] 2019-06-25 22:17:54,128: _ready: http://dc5b429f784e:41539/
[rospy.init][INFO] 2019-06-25 22:17:54,129: ROS Slave URI: [http://dc5b429f784e:41539/]
[xmlrpc][INFO] 2019-06-25 22:17:54,130: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 22:17:54,139: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-25 22:17:54,139: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-25 22:17:54,230: registered with master
[rospy.rosout][INFO] 2019-06-25 22:17:54,230: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 22:17:54,237: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 22:17:54,241: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 22:17:54,248: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 22:17:54,274: topic[/clock] adding connection to [http://dc5b429f784e:36377/], count 0
[rospy.internal][INFO] 2019-06-25 22:17:54,387: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-25 22:17:54,487: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2019-06-25 22:18:21,591: Unable to initiate TCP/IP socket to dc5b429f784e:35561 (http://dc5b429f784e:36377/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 35561 to [172.17.0.2:51678 on socket 9]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:18:22,594: Unable to initiate TCP/IP socket to dc5b429f784e:35561 (http://dc5b429f784e:36377/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 35561 to [172.17.0.2:51750 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:18:24,597: Unable to initiate TCP/IP socket to dc5b429f784e:35561 (http://dc5b429f784e:36377/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 35561 to [172.17.0.2:51756 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:18:28,602: Unable to initiate TCP/IP socket to dc5b429f784e:35561 (http://dc5b429f784e:36377/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 35561 to [172.17.0.2:51758 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][INFO] 2019-06-25 22:18:29,801: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 22:18:35,620: topic[/clock] adding connection to [http://dc5b429f784e:42613/], count 1
[rospy.internal][WARNING] 2019-06-25 22:18:36,606: Unknown error initiating TCP/IP socket to dc5b429f784e:35561 (http://dc5b429f784e:36377/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 22:18:36,606: topic[/clock] removing connection to http://dc5b429f784e:36377/
[rospy.internal][INFO] 2019-06-25 22:18:37,416: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][ERROR] 2019-06-25 22:20:08,612: Unable to initiate TCP/IP socket to dc5b429f784e:36373 (http://dc5b429f784e:42613/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 36373 to [172.17.0.2:54068 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:20:09,614: Unable to initiate TCP/IP socket to dc5b429f784e:36373 (http://dc5b429f784e:42613/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 36373 to [172.17.0.2:54136 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:20:11,617: Unable to initiate TCP/IP socket to dc5b429f784e:36373 (http://dc5b429f784e:42613/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 36373 to [172.17.0.2:54138 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:20:15,619: Unable to initiate TCP/IP socket to dc5b429f784e:36373 (http://dc5b429f784e:42613/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 36373 to [172.17.0.2:54140 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][WARNING] 2019-06-25 22:20:23,627: Unknown error initiating TCP/IP socket to dc5b429f784e:36373 (http://dc5b429f784e:42613/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 22:20:23,628: topic[/clock] removing connection to http://dc5b429f784e:42613/
[rospy.internal][INFO] 2019-06-25 22:20:23,762: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 22:20:47,543: topic[/clock] adding connection to [http://dc5b429f784e:41057/], count 0
[rospy.internal][INFO] 2019-06-25 22:20:48,686: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][ERROR] 2019-06-25 22:21:48,161: Unable to initiate TCP/IP socket to dc5b429f784e:42089 (http://dc5b429f784e:41057/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 42089 to [172.17.0.2:42160 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:21:49,163: Unable to initiate TCP/IP socket to dc5b429f784e:42089 (http://dc5b429f784e:41057/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 42089 to [172.17.0.2:42226 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:21:51,166: Unable to initiate TCP/IP socket to dc5b429f784e:42089 (http://dc5b429f784e:41057/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 42089 to [172.17.0.2:42228 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][INFO] 2019-06-25 22:21:53,079: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][WARNING] 2019-06-25 22:21:55,170: Unknown error initiating TCP/IP socket to dc5b429f784e:42089 (http://dc5b429f784e:41057/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 22:21:55,170: topic[/clock] removing connection to http://dc5b429f784e:41057/
[rospy.internal][INFO] 2019-06-25 22:21:56,755: topic[/clock] adding connection to [http://dc5b429f784e:40577/], count 0
[rospy.internal][INFO] 2019-06-25 22:21:58,168: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][ERROR] 2019-06-25 22:24:25,848: Unable to initiate TCP/IP socket to dc5b429f784e:36273 (http://dc5b429f784e:40577/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 36273 to [172.17.0.2:50522 on socket 18]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:24:26,850: Unable to initiate TCP/IP socket to dc5b429f784e:36273 (http://dc5b429f784e:40577/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 36273 to [172.17.0.2:50588 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:24:28,855: Unable to initiate TCP/IP socket to dc5b429f784e:36273 (http://dc5b429f784e:40577/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 36273 to [172.17.0.2:50590 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:24:32,860: Unable to initiate TCP/IP socket to dc5b429f784e:36273 (http://dc5b429f784e:40577/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 36273 to [172.17.0.2:50592 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:24:40,865: Unable to initiate TCP/IP socket to dc5b429f784e:36273 (http://dc5b429f784e:40577/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 36273 to [172.17.0.2:50594 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:24:56,879: Unable to initiate TCP/IP socket to dc5b429f784e:36273 (http://dc5b429f784e:40577/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 36273 to [172.17.0.2:50596 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][INFO] 2019-06-25 22:25:17,879: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 22:25:24,049: topic[/clock] adding connection to [http://dc5b429f784e:39293/], count 1
[rospy.internal][INFO] 2019-06-25 22:25:25,812: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][WARNING] 2019-06-25 22:25:28,900: Unknown error initiating TCP/IP socket to dc5b429f784e:36273 (http://dc5b429f784e:40577/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 22:25:28,900: topic[/clock] removing connection to http://dc5b429f784e:40577/
[rospy.internal][ERROR] 2019-06-25 22:26:12,718: Unable to initiate TCP/IP socket to dc5b429f784e:37745 (http://dc5b429f784e:39293/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 37745 to [172.17.0.2:42164 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:26:13,720: Unable to initiate TCP/IP socket to dc5b429f784e:37745 (http://dc5b429f784e:39293/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 37745 to [172.17.0.2:42236 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:26:15,721: Unable to initiate TCP/IP socket to dc5b429f784e:37745 (http://dc5b429f784e:39293/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 37745 to [172.17.0.2:42240 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:26:19,723: Unable to initiate TCP/IP socket to dc5b429f784e:37745 (http://dc5b429f784e:39293/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 37745 to [172.17.0.2:42244 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][INFO] 2019-06-25 22:26:27,621: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][WARNING] 2019-06-25 22:26:27,731: Unknown error initiating TCP/IP socket to dc5b429f784e:37745 (http://dc5b429f784e:39293/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 22:26:27,732: topic[/clock] removing connection to http://dc5b429f784e:39293/
[rospy.internal][INFO] 2019-06-25 22:26:35,601: topic[/clock] adding connection to [http://dc5b429f784e:39405/], count 0
[rospy.internal][INFO] 2019-06-25 22:26:36,971: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][ERROR] 2019-06-25 22:30:22,978: Unable to initiate TCP/IP socket to dc5b429f784e:51679 (http://dc5b429f784e:39405/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 51679 to [172.17.0.2:45956 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:30:23,979: Unable to initiate TCP/IP socket to dc5b429f784e:51679 (http://dc5b429f784e:39405/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 51679 to [172.17.0.2:46028 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:30:25,982: Unable to initiate TCP/IP socket to dc5b429f784e:51679 (http://dc5b429f784e:39405/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 51679 to [172.17.0.2:46032 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:30:29,988: Unable to initiate TCP/IP socket to dc5b429f784e:51679 (http://dc5b429f784e:39405/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 51679 to [172.17.0.2:46074 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:30:37,993: Unable to initiate TCP/IP socket to dc5b429f784e:51679 (http://dc5b429f784e:39405/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 51679 to [172.17.0.2:46316 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][INFO] 2019-06-25 22:30:41,279: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 22:30:45,698: topic[/clock] adding connection to [http://dc5b429f784e:38543/], count 1
[rospy.internal][INFO] 2019-06-25 22:30:47,290: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][WARNING] 2019-06-25 22:30:54,003: Unknown error initiating TCP/IP socket to dc5b429f784e:51679 (http://dc5b429f784e:39405/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 22:30:54,005: topic[/clock] removing connection to http://dc5b429f784e:39405/
[rospy.internal][ERROR] 2019-06-25 22:32:02,618: Unable to initiate TCP/IP socket to dc5b429f784e:53673 (http://dc5b429f784e:38543/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 53673 to [172.17.0.2:40418 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:32:03,620: Unable to initiate TCP/IP socket to dc5b429f784e:53673 (http://dc5b429f784e:38543/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 53673 to [172.17.0.2:40490 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:32:05,623: Unable to initiate TCP/IP socket to dc5b429f784e:53673 (http://dc5b429f784e:38543/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 53673 to [172.17.0.2:40494 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][INFO] 2019-06-25 22:32:06,261: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][WARNING] 2019-06-25 22:32:09,624: Unknown error initiating TCP/IP socket to dc5b429f784e:53673 (http://dc5b429f784e:38543/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 22:32:09,625: topic[/clock] removing connection to http://dc5b429f784e:38543/
[rospy.internal][INFO] 2019-06-25 22:32:14,231: topic[/clock] adding connection to [http://dc5b429f784e:33987/], count 0
[rospy.internal][INFO] 2019-06-25 22:32:15,977: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][ERROR] 2019-06-25 22:35:08,583: Unable to initiate TCP/IP socket to dc5b429f784e:41005 (http://dc5b429f784e:33987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 41005 to [172.17.0.2:41228 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:35:09,585: Unable to initiate TCP/IP socket to dc5b429f784e:41005 (http://dc5b429f784e:33987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 41005 to [172.17.0.2:41302 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:35:11,588: Unable to initiate TCP/IP socket to dc5b429f784e:41005 (http://dc5b429f784e:33987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 41005 to [172.17.0.2:41342 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:35:15,591: Unable to initiate TCP/IP socket to dc5b429f784e:41005 (http://dc5b429f784e:33987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 41005 to [172.17.0.2:41344 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][WARNING] 2019-06-25 22:35:23,603: Unknown error initiating TCP/IP socket to dc5b429f784e:41005 (http://dc5b429f784e:33987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 22:35:23,603: topic[/clock] removing connection to http://dc5b429f784e:33987/
[rospy.internal][INFO] 2019-06-25 22:35:23,885: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 22:35:31,757: topic[/clock] adding connection to [http://dc5b429f784e:38525/], count 0
[rospy.internal][INFO] 2019-06-25 22:35:33,448: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][ERROR] 2019-06-25 22:37:13,061: Unable to initiate TCP/IP socket to dc5b429f784e:50645 (http://dc5b429f784e:38525/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 50645 to [172.17.0.2:41738 on socket 9]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:37:14,063: Unable to initiate TCP/IP socket to dc5b429f784e:50645 (http://dc5b429f784e:38525/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 50645 to [172.17.0.2:41816 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:37:16,064: Unable to initiate TCP/IP socket to dc5b429f784e:50645 (http://dc5b429f784e:38525/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 50645 to [172.17.0.2:41820 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][INFO] 2019-06-25 22:37:16,325: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][WARNING] 2019-06-25 22:37:20,068: Unknown error initiating TCP/IP socket to dc5b429f784e:50645 (http://dc5b429f784e:38525/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 22:37:20,068: topic[/clock] removing connection to http://dc5b429f784e:38525/
[rospy.internal][INFO] 2019-06-25 22:37:20,644: topic[/clock] adding connection to [http://dc5b429f784e:35135/], count 0
[rospy.internal][INFO] 2019-06-25 22:37:22,454: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][ERROR] 2019-06-25 22:38:18,764: Unable to initiate TCP/IP socket to dc5b429f784e:39199 (http://dc5b429f784e:35135/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 39199 to [172.17.0.2:50852 on socket 9]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:38:19,766: Unable to initiate TCP/IP socket to dc5b429f784e:39199 (http://dc5b429f784e:35135/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 39199 to [172.17.0.2:50918 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:38:21,769: Unable to initiate TCP/IP socket to dc5b429f784e:39199 (http://dc5b429f784e:35135/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 39199 to [172.17.0.2:50920 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:38:25,774: Unable to initiate TCP/IP socket to dc5b429f784e:39199 (http://dc5b429f784e:35135/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 39199 to [172.17.0.2:50922 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][INFO] 2019-06-25 22:38:33,703: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][WARNING] 2019-06-25 22:38:33,775: Unknown error initiating TCP/IP socket to dc5b429f784e:39199 (http://dc5b429f784e:35135/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-25 22:38:33,776: topic[/clock] removing connection to http://dc5b429f784e:35135/
[rospy.internal][INFO] 2019-06-25 22:38:42,210: topic[/clock] adding connection to [http://dc5b429f784e:43337/], count 0
[rospy.internal][INFO] 2019-06-25 22:38:43,835: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][ERROR] 2019-06-25 22:42:33,135: Unable to initiate TCP/IP socket to dc5b429f784e:48915 (http://dc5b429f784e:43337/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 48915 to [172.17.0.2:36778 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:42:34,137: Unable to initiate TCP/IP socket to dc5b429f784e:48915 (http://dc5b429f784e:43337/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 48915 to [172.17.0.2:36850 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-25 22:42:36,140: Unable to initiate TCP/IP socket to dc5b429f784e:48915 (http://dc5b429f784e:43337/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 48915 to [172.17.0.2:36854 on socket 16]] [/teleop_twist_keyboard].

[rospy.core][INFO] 2019-06-25 22:42:38,073: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 22:42:38,077: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 22:42:38,077: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-25 22:42:38,078: topic[/clock] removing connection to http://dc5b429f784e:43337/
[rospy.impl.masterslave][INFO] 2019-06-25 22:42:38,078: atexit
[rospy.client][INFO] 2019-06-26 09:09:20,084: init_node, name[/teleop_twist_keyboard], pid[2388]
[xmlrpc][INFO] 2019-06-26 09:09:20,102: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-26 09:09:20,104: Started XML-RPC server [http://dc5b429f784e:45167/]
[rospy.impl.masterslave][INFO] 2019-06-26 09:09:20,104: _ready: http://dc5b429f784e:45167/
[rospy.init][INFO] 2019-06-26 09:09:20,104: ROS Slave URI: [http://dc5b429f784e:45167/]
[xmlrpc][INFO] 2019-06-26 09:09:20,105: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-26 09:09:20,107: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-26 09:09:20,108: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-26 09:09:20,206: registered with master
[rospy.rosout][INFO] 2019-06-26 09:09:20,207: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-26 09:09:20,211: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-26 09:09:20,214: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-26 09:09:20,219: connected to core topic /clock
[rospy.internal][INFO] 2019-06-26 09:09:20,229: topic[/clock] adding connection to [http://dc5b429f784e:42633/], count 0
[rospy.internal][INFO] 2019-06-26 09:09:20,432: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-26 09:09:20,453: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-26 09:09:35,108: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-26 09:09:35,115: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-26 09:09:35,116: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-26 09:09:35,116: topic[/clock] removing connection to http://dc5b429f784e:42633/
[rospy.impl.masterslave][INFO] 2019-06-26 09:09:35,117: atexit
[rospy.internal][ERROR] 2019-06-26 09:09:35,119: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 729, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.core][INFO] 2019-06-26 09:09:35,252: signal_shutdown [signal-2]
[rospy.client][INFO] 2019-06-26 09:10:03,807: init_node, name[/teleop_twist_keyboard], pid[2587]
[xmlrpc][INFO] 2019-06-26 09:10:03,807: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2019-06-26 09:10:03,809: ROS Slave URI: [http://dc5b429f784e:41153/]
[xmlrpc][INFO] 2019-06-26 09:10:03,808: Started XML-RPC server [http://dc5b429f784e:41153/]
[rospy.impl.masterslave][INFO] 2019-06-26 09:10:03,810: _ready: http://dc5b429f784e:41153/
[xmlrpc][INFO] 2019-06-26 09:10:03,810: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-26 09:10:03,812: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-26 09:10:03,812: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-26 09:10:03,910: registered with master
[rospy.rosout][INFO] 2019-06-26 09:10:03,910: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-26 09:10:03,913: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-26 09:10:03,917: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-26 09:10:03,925: connected to core topic /clock
[rospy.internal][INFO] 2019-06-26 09:10:03,936: topic[/clock] adding connection to [http://dc5b429f784e:42633/], count 0
[rospy.internal][INFO] 2019-06-26 09:10:04,038: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-26 09:10:04,152: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-26 09:11:20,182: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-26 09:11:20,188: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-26 09:11:20,189: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-26 09:11:20,190: topic[/clock] removing connection to http://dc5b429f784e:42633/
[rospy.internal][WARNING] 2019-06-26 09:11:20,191: Unknown error initiating TCP/IP socket to dc5b429f784e:48563 (http://dc5b429f784e:42633/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.impl.masterslave][INFO] 2019-06-26 09:11:20,190: atexit
[rospy.core][INFO] 2019-06-26 09:11:20,347: signal_shutdown [signal-2]
[rospy.core][INFO] 2019-06-26 09:11:20,495: signal_shutdown [signal-2]
[rospy.client][INFO] 2019-06-26 09:22:26,386: init_node, name[/teleop_twist_keyboard], pid[3405]
[xmlrpc][INFO] 2019-06-26 09:22:26,387: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-26 09:22:26,388: Started XML-RPC server [http://dc5b429f784e:34871/]
[rospy.impl.masterslave][INFO] 2019-06-26 09:22:26,388: _ready: http://dc5b429f784e:34871/
[rospy.init][INFO] 2019-06-26 09:22:26,389: ROS Slave URI: [http://dc5b429f784e:34871/]
[xmlrpc][INFO] 2019-06-26 09:22:26,389: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-26 09:22:26,391: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-26 09:22:26,391: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-26 09:22:26,490: registered with master
[rospy.rosout][INFO] 2019-06-26 09:22:26,490: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-26 09:22:26,493: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-26 09:22:26,495: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-26 09:22:26,501: connected to core topic /clock
[rospy.internal][INFO] 2019-06-26 09:22:26,519: topic[/clock] adding connection to [http://dc5b429f784e:38345/], count 0
[rospy.internal][INFO] 2019-06-26 09:22:26,706: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-06-26 09:22:26,722: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][ERROR] 2019-06-26 09:51:31,706: Unable to initiate TCP/IP socket to dc5b429f784e:49917 (http://dc5b429f784e:38345/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 49917 to [172.17.0.2:60136 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-26 09:51:32,708: Unable to initiate TCP/IP socket to dc5b429f784e:49917 (http://dc5b429f784e:38345/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 49917 to [172.17.0.2:60204 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-26 09:51:34,711: Unable to initiate TCP/IP socket to dc5b429f784e:49917 (http://dc5b429f784e:38345/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 49917 to [172.17.0.2:60206 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-06-26 09:51:38,716: Unable to initiate TCP/IP socket to dc5b429f784e:49917 (http://dc5b429f784e:38345/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 49917 to [172.17.0.2:60208 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][WARNING] 2019-06-26 09:51:46,724: Unknown error initiating TCP/IP socket to dc5b429f784e:49917 (http://dc5b429f784e:38345/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-06-26 09:51:46,724: topic[/clock] removing connection to http://dc5b429f784e:38345/
[rospy.internal][INFO] 2019-06-26 09:51:46,949: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-26 09:51:46,949: topic[/cmd_vel] removing connection to /gazebo
[rospy.core][INFO] 2019-06-26 09:55:26,059: signal_shutdown [atexit]
[rospy.registration][WARNING] 2019-06-26 09:55:26,064: unclean shutdown
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/registration.py", line 374, in cleanup
    multi()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1006, in __call__
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 99] Cannot assign requested address

[rospy.impl.masterslave][INFO] 2019-06-26 09:55:26,065: atexit
[rospy.client][INFO] 2019-06-26 10:47:27,188: init_node, name[/teleop_twist_keyboard], pid[8607]
[xmlrpc][INFO] 2019-06-26 10:47:27,189: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-26 10:47:27,189: Started XML-RPC server [http://dc5b429f784e:40455/]
[rospy.impl.masterslave][INFO] 2019-06-26 10:47:27,189: _ready: http://dc5b429f784e:40455/
[rospy.init][INFO] 2019-06-26 10:47:27,192: ROS Slave URI: [http://dc5b429f784e:40455/]
[rospy.registration][INFO] 2019-06-26 10:47:27,203: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-26 10:47:27,203: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[xmlrpc][INFO] 2019-06-26 10:47:27,205: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2019-06-26 10:47:27,292: registered with master
[rospy.rosout][INFO] 2019-06-26 10:47:27,292: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-26 10:47:27,295: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-26 10:47:27,298: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-26 10:47:27,303: connected to core topic /clock
[rospy.internal][INFO] 2019-06-26 10:47:27,345: topic[/clock] adding connection to [http://dc5b429f784e:45131/], count 0
[rospy.internal][INFO] 2019-06-26 10:47:27,543: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-06-26 10:47:27,551: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.core][INFO] 2019-06-26 10:59:25,679: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-26 10:59:25,685: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-26 10:59:25,685: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-26 10:59:25,686: topic[/clock] removing connection to http://dc5b429f784e:45131/
[rospy.impl.masterslave][INFO] 2019-06-26 10:59:25,686: atexit
[rospy.internal][ERROR] 2019-06-26 10:59:25,687: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 729, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.client][INFO] 2019-06-28 13:26:47,081: init_node, name[/teleop_twist_keyboard], pid[769]
[xmlrpc][INFO] 2019-06-28 13:26:47,084: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-28 13:26:47,084: Started XML-RPC server [http://dc5b429f784e:43467/]
[rospy.impl.masterslave][INFO] 2019-06-28 13:26:47,085: _ready: http://dc5b429f784e:43467/
[rospy.init][INFO] 2019-06-28 13:26:47,085: ROS Slave URI: [http://dc5b429f784e:43467/]
[xmlrpc][INFO] 2019-06-28 13:26:47,086: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-28 13:26:47,087: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-28 13:26:47,087: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-28 13:26:47,186: registered with master
[rospy.rosout][INFO] 2019-06-28 13:26:47,187: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-28 13:26:47,189: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-28 13:26:47,191: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-28 13:26:47,196: connected to core topic /clock
[rospy.internal][INFO] 2019-06-28 13:26:47,208: topic[/clock] adding connection to [http://dc5b429f784e:34841/], count 0
[rospy.internal][INFO] 2019-06-28 13:26:47,309: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-28 13:26:47,396: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-28 13:27:05,758: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-28 13:27:05,764: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-28 13:27:05,764: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-28 13:27:05,765: topic[/clock] removing connection to http://dc5b429f784e:34841/
[rospy.impl.masterslave][INFO] 2019-06-28 13:27:05,766: atexit
[rospy.internal][ERROR] 2019-06-28 13:27:05,767: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 729, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.client][INFO] 2019-06-28 13:50:25,053: init_node, name[/teleop_twist_keyboard], pid[2908]
[xmlrpc][INFO] 2019-06-28 13:50:25,054: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-28 13:50:25,054: Started XML-RPC server [http://dc5b429f784e:42359/]
[rospy.init][INFO] 2019-06-28 13:50:25,055: ROS Slave URI: [http://dc5b429f784e:42359/]
[rospy.impl.masterslave][INFO] 2019-06-28 13:50:25,055: _ready: http://dc5b429f784e:42359/
[xmlrpc][INFO] 2019-06-28 13:50:25,056: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-28 13:50:25,058: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-28 13:50:25,058: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-28 13:50:25,156: registered with master
[rospy.rosout][INFO] 2019-06-28 13:50:25,156: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-28 13:50:25,170: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-28 13:50:25,175: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-28 13:50:25,180: connected to core topic /clock
[rospy.internal][INFO] 2019-06-28 13:50:25,228: topic[/clock] adding connection to [http://dc5b429f784e:34657/], count 0
[rospy.internal][INFO] 2019-06-28 13:50:25,331: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-28 13:50:25,375: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-28 13:50:37,472: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-28 13:50:37,488: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-28 13:50:37,489: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-28 13:50:37,490: topic[/clock] removing connection to http://dc5b429f784e:34657/
[rospy.impl.masterslave][INFO] 2019-06-28 13:50:37,490: atexit
[rospy.internal][ERROR] 2019-06-28 13:50:37,491: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 729, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.client][INFO] 2019-06-28 14:26:34,944: init_node, name[/teleop_twist_keyboard], pid[10404]
[xmlrpc][INFO] 2019-06-28 14:26:34,945: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-28 14:26:34,945: Started XML-RPC server [http://dc5b429f784e:40453/]
[rospy.impl.masterslave][INFO] 2019-06-28 14:26:34,945: _ready: http://dc5b429f784e:40453/
[xmlrpc][INFO] 2019-06-28 14:26:34,946: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-28 14:26:34,946: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-28 14:26:34,947: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-28 14:26:34,949: ROS Slave URI: [http://dc5b429f784e:40453/]
[rospy.init][INFO] 2019-06-28 14:26:35,050: registered with master
[rospy.rosout][INFO] 2019-06-28 14:26:35,050: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-28 14:26:35,058: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-28 14:26:35,065: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-28 14:26:35,076: connected to core topic /clock
[rospy.internal][INFO] 2019-06-28 14:26:35,117: topic[/clock] adding connection to [http://dc5b429f784e:42047/], count 0
[rospy.internal][INFO] 2019-06-28 14:26:35,219: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-28 14:26:35,267: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-28 14:26:47,948: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-28 14:26:47,957: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-28 14:26:47,957: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-28 14:26:47,958: topic[/clock] removing connection to http://dc5b429f784e:42047/
[rospy.internal][WARNING] 2019-06-28 14:26:47,959: Unknown error initiating TCP/IP socket to dc5b429f784e:58081 (http://dc5b429f784e:42047/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2019-06-28 14:26:47,961: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2019-06-28 14:26:47,961: atexit
[rospy.client][INFO] 2019-06-29 15:25:47,798: init_node, name[/teleop_twist_keyboard], pid[1907]
[xmlrpc][INFO] 2019-06-29 15:25:47,801: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-29 15:25:47,802: Started XML-RPC server [http://dc5b429f784e:36857/]
[rospy.init][INFO] 2019-06-29 15:25:47,804: ROS Slave URI: [http://dc5b429f784e:36857/]
[rospy.impl.masterslave][INFO] 2019-06-29 15:25:47,804: _ready: http://dc5b429f784e:36857/
[xmlrpc][INFO] 2019-06-29 15:25:47,807: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-29 15:25:47,808: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-29 15:25:47,808: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-29 15:25:47,905: registered with master
[rospy.rosout][INFO] 2019-06-29 15:25:47,906: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-29 15:25:47,911: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-29 15:25:47,915: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-29 15:25:47,921: connected to core topic /clock
[rospy.internal][INFO] 2019-06-29 15:25:47,930: topic[/clock] adding connection to [http://dc5b429f784e:46437/], count 0
[rospy.internal][INFO] 2019-06-29 15:25:48,132: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-29 15:25:48,178: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-29 15:30:08,259: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-29 15:30:08,262: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-29 15:30:08,262: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-29 15:30:08,263: topic[/clock] removing connection to http://dc5b429f784e:46437/
[rospy.impl.masterslave][INFO] 2019-06-29 15:30:08,263: atexit
[rospy.client][INFO] 2019-06-30 12:23:01,587: init_node, name[/teleop_twist_keyboard], pid[5645]
[xmlrpc][INFO] 2019-06-30 12:23:01,589: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2019-06-30 12:23:01,591: ROS Slave URI: [http://dc5b429f784e:37621/]
[xmlrpc][INFO] 2019-06-30 12:23:01,592: Started XML-RPC server [http://dc5b429f784e:37621/]
[rospy.impl.masterslave][INFO] 2019-06-30 12:23:01,592: _ready: http://dc5b429f784e:37621/
[xmlrpc][INFO] 2019-06-30 12:23:01,594: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-30 12:23:01,596: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-06-30 12:23:01,597: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-06-30 12:23:01,692: registered with master
[rospy.rosout][INFO] 2019-06-30 12:23:01,692: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-30 12:23:01,695: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-30 12:23:01,698: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-30 12:23:01,712: connected to core topic /clock
[rospy.internal][INFO] 2019-06-30 12:23:01,720: topic[/clock] adding connection to [http://dc5b429f784e:44493/], count 0
[rospy.internal][INFO] 2019-06-30 12:23:01,822: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-06-30 12:23:01,916: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-30 12:23:06,855: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-30 12:23:06,882: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-30 12:23:06,885: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-06-30 12:23:06,887: topic[/clock] removing connection to http://dc5b429f784e:44493/
[rospy.impl.masterslave][INFO] 2019-06-30 12:23:06,888: atexit
[rospy.client][INFO] 2019-07-02 12:58:33,607: init_node, name[/teleop_twist_keyboard], pid[7062]
[xmlrpc][INFO] 2019-07-02 12:58:33,608: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-07-02 12:58:33,608: Started XML-RPC server [http://f6566a55c2b3:34671/]
[rospy.init][INFO] 2019-07-02 12:58:33,609: ROS Slave URI: [http://f6566a55c2b3:34671/]
[rospy.impl.masterslave][INFO] 2019-07-02 12:58:33,609: _ready: http://f6566a55c2b3:34671/
[xmlrpc][INFO] 2019-07-02 12:58:33,612: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-07-02 12:58:33,613: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-07-02 12:58:33,613: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-07-02 12:58:33,712: registered with master
[rospy.rosout][INFO] 2019-07-02 12:58:33,712: initializing /rosout core topic
[rospy.rosout][INFO] 2019-07-02 12:58:33,714: connected to core topic /rosout
[rospy.simtime][INFO] 2019-07-02 12:58:33,716: initializing /clock core topic
[rospy.simtime][INFO] 2019-07-02 12:58:33,720: connected to core topic /clock
[rospy.internal][INFO] 2019-07-02 12:58:33,736: topic[/clock] adding connection to [http://f6566a55c2b3:35049/], count 0
[rospy.internal][INFO] 2019-07-02 12:58:33,948: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2019-07-02 12:58:58,336: Unable to initiate TCP/IP socket to f6566a55c2b3:39317 (http://f6566a55c2b3:35049/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 39317 to [172.17.0.2:57780 on socket 17]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-07-02 12:58:59,338: Unable to initiate TCP/IP socket to f6566a55c2b3:39317 (http://f6566a55c2b3:35049/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 39317 to [172.17.0.2:57866 on socket 16]] [/teleop_twist_keyboard].

[rospy.internal][ERROR] 2019-07-02 12:59:01,341: Unable to initiate TCP/IP socket to f6566a55c2b3:39317 (http://f6566a55c2b3:35049/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 39317 to [172.17.0.2:57872 on socket 16]] [/teleop_twist_keyboard].

[rospy.core][INFO] 2019-07-02 12:59:01,546: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-07-02 12:59:01,549: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-07-02 12:59:01,549: topic[/clock] removing connection to http://f6566a55c2b3:35049/
[rospy.impl.masterslave][INFO] 2019-07-02 12:59:01,550: atexit
[rospy.client][INFO] 2019-07-02 13:00:42,917: init_node, name[/teleop_twist_keyboard], pid[7733]
[xmlrpc][INFO] 2019-07-02 13:00:42,918: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-07-02 13:00:42,918: Started XML-RPC server [http://f6566a55c2b3:42099/]
[rospy.impl.masterslave][INFO] 2019-07-02 13:00:42,919: _ready: http://f6566a55c2b3:42099/
[rospy.init][INFO] 2019-07-02 13:00:42,919: ROS Slave URI: [http://f6566a55c2b3:42099/]
[xmlrpc][INFO] 2019-07-02 13:00:42,919: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-07-02 13:00:42,920: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-07-02 13:00:42,920: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-07-02 13:00:43,019: registered with master
[rospy.rosout][INFO] 2019-07-02 13:00:43,020: initializing /rosout core topic
[rospy.rosout][INFO] 2019-07-02 13:00:43,023: connected to core topic /rosout
[rospy.simtime][INFO] 2019-07-02 13:00:43,025: initializing /clock core topic
[rospy.simtime][INFO] 2019-07-02 13:00:43,031: connected to core topic /clock
[rospy.internal][INFO] 2019-07-02 13:00:43,040: topic[/clock] adding connection to [http://f6566a55c2b3:46715/], count 0
[rospy.internal][INFO] 2019-07-02 13:00:43,256: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-07-02 13:01:07,158: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-07-02 13:01:07,164: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-07-02 13:01:07,165: topic[/clock] removing connection to http://f6566a55c2b3:46715/
[rospy.impl.masterslave][INFO] 2019-07-02 13:01:07,166: atexit
[rospy.client][INFO] 2019-07-02 13:01:47,167: init_node, name[/teleop_twist_keyboard], pid[8002]
[xmlrpc][INFO] 2019-07-02 13:01:47,167: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2019-07-02 13:01:47,168: ROS Slave URI: [http://f6566a55c2b3:39677/]
[xmlrpc][INFO] 2019-07-02 13:01:47,168: Started XML-RPC server [http://f6566a55c2b3:39677/]
[rospy.impl.masterslave][INFO] 2019-07-02 13:01:47,169: _ready: http://f6566a55c2b3:39677/
[xmlrpc][INFO] 2019-07-02 13:01:47,170: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-07-02 13:01:47,170: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-07-02 13:01:47,171: Registering publisher topic [/robot/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-07-02 13:01:47,269: registered with master
[rospy.rosout][INFO] 2019-07-02 13:01:47,269: initializing /rosout core topic
[rospy.rosout][INFO] 2019-07-02 13:01:47,272: connected to core topic /rosout
[rospy.simtime][INFO] 2019-07-02 13:01:47,274: initializing /clock core topic
[rospy.simtime][INFO] 2019-07-02 13:01:47,277: connected to core topic /clock
[rospy.internal][INFO] 2019-07-02 13:01:47,291: topic[/clock] adding connection to [http://f6566a55c2b3:46715/], count 0
[rospy.internal][INFO] 2019-07-02 13:01:47,393: topic[/robot/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-07-02 13:01:47,489: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-07-02 13:01:52,044: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-07-02 13:01:52,050: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-07-02 13:01:52,051: topic[/robot/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-07-02 13:01:52,052: topic[/clock] removing connection to http://f6566a55c2b3:46715/
[rospy.impl.masterslave][INFO] 2019-07-02 13:01:52,052: atexit
[rospy.client][INFO] 2019-07-02 13:01:54,611: init_node, name[/teleop_twist_keyboard], pid[8035]
[xmlrpc][INFO] 2019-07-02 13:01:54,622: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-07-02 13:01:54,627: Started XML-RPC server [http://f6566a55c2b3:46425/]
[rospy.init][INFO] 2019-07-02 13:01:54,627: ROS Slave URI: [http://f6566a55c2b3:46425/]
[rospy.impl.masterslave][INFO] 2019-07-02 13:01:54,627: _ready: http://f6566a55c2b3:46425/
[xmlrpc][INFO] 2019-07-02 13:01:54,628: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-07-02 13:01:54,629: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-07-02 13:01:54,630: Registering publisher topic [/robot/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-07-02 13:01:54,728: registered with master
[rospy.rosout][INFO] 2019-07-02 13:01:54,728: initializing /rosout core topic
[rospy.rosout][INFO] 2019-07-02 13:01:54,730: connected to core topic /rosout
[rospy.simtime][INFO] 2019-07-02 13:01:54,732: initializing /clock core topic
[rospy.simtime][INFO] 2019-07-02 13:01:54,736: connected to core topic /clock
[rospy.internal][INFO] 2019-07-02 13:01:54,750: topic[/clock] adding connection to [http://f6566a55c2b3:46715/], count 0
[rospy.internal][INFO] 2019-07-02 13:01:54,853: topic[/robot/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-07-02 13:01:54,953: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-07-02 13:02:23,821: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-07-02 13:02:23,832: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-07-02 13:02:23,833: topic[/robot/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-07-02 13:02:23,834: topic[/clock] removing connection to http://f6566a55c2b3:46715/
[rospy.impl.masterslave][INFO] 2019-07-02 13:02:23,835: atexit
[rospy.core][INFO] 2019-07-02 13:02:24,272: signal_shutdown [signal-2]
[rospy.client][INFO] 2019-07-02 13:20:20,865: init_node, name[/teleop_twist_keyboard], pid[12179]
[xmlrpc][INFO] 2019-07-02 13:20:20,866: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-07-02 13:20:20,866: Started XML-RPC server [http://f6566a55c2b3:34185/]
[rospy.init][INFO] 2019-07-02 13:20:20,867: ROS Slave URI: [http://f6566a55c2b3:34185/]
[rospy.impl.masterslave][INFO] 2019-07-02 13:20:20,867: _ready: http://f6566a55c2b3:34185/
[xmlrpc][INFO] 2019-07-02 13:20:20,868: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-07-02 13:20:20,869: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-07-02 13:20:20,869: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-07-02 13:20:20,968: registered with master
[rospy.rosout][INFO] 2019-07-02 13:20:20,968: initializing /rosout core topic
[rospy.rosout][INFO] 2019-07-02 13:20:20,972: connected to core topic /rosout
[rospy.simtime][INFO] 2019-07-02 13:20:20,976: initializing /clock core topic
[rospy.simtime][INFO] 2019-07-02 13:20:20,982: connected to core topic /clock
[rospy.internal][INFO] 2019-07-02 13:20:20,993: topic[/clock] adding connection to [http://f6566a55c2b3:45957/], count 0
[rospy.internal][INFO] 2019-07-02 13:20:21,097: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.core][INFO] 2019-07-02 13:20:34,920: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-07-02 13:20:34,927: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-07-02 13:20:34,928: topic[/clock] removing connection to http://f6566a55c2b3:45957/
[rospy.impl.masterslave][INFO] 2019-07-02 13:20:34,928: atexit
[rospy.client][INFO] 2019-07-02 13:53:58,454: init_node, name[/teleop_twist_keyboard], pid[19531]
[xmlrpc][INFO] 2019-07-02 13:53:58,472: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-07-02 13:53:58,473: Started XML-RPC server [http://f6566a55c2b3:32957/]
[rospy.impl.masterslave][INFO] 2019-07-02 13:53:58,473: _ready: http://f6566a55c2b3:32957/
[rospy.init][INFO] 2019-07-02 13:53:58,474: ROS Slave URI: [http://f6566a55c2b3:32957/]
[xmlrpc][INFO] 2019-07-02 13:53:58,474: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-07-02 13:53:58,475: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-07-02 13:53:58,475: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-07-02 13:53:58,574: registered with master
[rospy.rosout][INFO] 2019-07-02 13:53:58,574: initializing /rosout core topic
[rospy.rosout][INFO] 2019-07-02 13:53:58,583: connected to core topic /rosout
[rospy.simtime][INFO] 2019-07-02 13:53:58,587: initializing /clock core topic
[rospy.simtime][INFO] 2019-07-02 13:53:58,593: connected to core topic /clock
[rospy.internal][INFO] 2019-07-02 13:53:58,644: topic[/clock] adding connection to [http://f6566a55c2b3:46705/], count 0
[rospy.internal][INFO] 2019-07-02 13:53:58,746: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-07-02 13:53:58,788: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-07-02 13:54:12,482: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-07-02 13:54:12,489: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-07-02 13:54:12,490: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2019-07-02 13:54:12,490: topic[/clock] removing connection to http://f6566a55c2b3:46705/
[rospy.impl.masterslave][INFO] 2019-07-02 13:54:12,491: atexit
[rospy.client][INFO] 2019-07-02 14:35:46,128: init_node, name[/teleop_twist_keyboard], pid[21251]
[xmlrpc][INFO] 2019-07-02 14:35:46,129: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-07-02 14:35:46,130: Started XML-RPC server [http://f6566a55c2b3:44631/]
[rospy.impl.masterslave][INFO] 2019-07-02 14:35:46,130: _ready: http://f6566a55c2b3:44631/
[xmlrpc][INFO] 2019-07-02 14:35:46,131: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2019-07-02 14:35:46,131: ROS Slave URI: [http://f6566a55c2b3:44631/]
[rospy.registration][INFO] 2019-07-02 14:35:46,133: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2019-07-02 14:35:46,133: Registering publisher topic [/cmd_vel] type [geometry_msgs/Twist] with master
[rospy.init][INFO] 2019-07-02 14:35:46,232: registered with master
[rospy.rosout][INFO] 2019-07-02 14:35:46,232: initializing /rosout core topic
[rospy.rosout][INFO] 2019-07-02 14:35:46,241: connected to core topic /rosout
[rospy.simtime][INFO] 2019-07-02 14:35:46,253: initializing /clock core topic
[rospy.simtime][INFO] 2019-07-02 14:35:46,264: connected to core topic /clock
[rospy.internal][INFO] 2019-07-02 14:35:46,314: topic[/clock] adding connection to [http://f6566a55c2b3:34745/], count 0
[rospy.internal][INFO] 2019-07-02 14:35:46,432: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2019-07-02 14:35:46,450: topic[/rosout] adding connection to [/rosout], count 0
