[rospy.client][INFO] 2019-06-25 13:34:18,484: init_node, name[/view_frames_72783_1561469658384], pid[72783]
[xmlrpc][INFO] 2019-06-25 13:34:18,491: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2019-06-25 13:34:18,492: ROS Slave URI: [http://dc5b429f784e:45739/]
[xmlrpc][INFO] 2019-06-25 13:34:18,491: Started XML-RPC server [http://dc5b429f784e:45739/]
[rospy.impl.masterslave][INFO] 2019-06-25 13:34:18,492: _ready: http://dc5b429f784e:45739/
[xmlrpc][INFO] 2019-06-25 13:34:18,494: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 13:34:18,495: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-06-25 13:34:18,596: registered with master
[rospy.rosout][INFO] 2019-06-25 13:34:18,596: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 13:34:18,601: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 13:34:18,604: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 13:34:18,610: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 13:34:18,670: topic[/tf] adding connection to [http://dc5b429f784e:39511/], count 0
[rospy.internal][INFO] 2019-06-25 13:34:18,686: topic[/tf] adding connection to [http://dc5b429f784e:36259/], count 1
[rospy.internal][INFO] 2019-06-25 13:34:18,695: topic[/tf] adding connection to [http://dc5b429f784e:38229/], count 2
[rospy.internal][INFO] 2019-06-25 13:34:18,698: topic[/tf] adding connection to [http://dc5b429f784e:46007/], count 3
[rospy.internal][INFO] 2019-06-25 13:34:18,700: topic[/clock] adding connection to [http://dc5b429f784e:39511/], count 0
[rospy.internal][INFO] 2019-06-25 13:34:18,812: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2019-06-25 13:34:23,731: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 13:34:23,739: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 13:34:23,740: topic[/clock] removing connection to http://dc5b429f784e:39511/
[rospy.internal][INFO] 2019-06-25 13:34:23,740: topic[/tf] removing connection to http://dc5b429f784e:39511/
[rospy.internal][INFO] 2019-06-25 13:34:23,741: topic[/tf] removing connection to http://dc5b429f784e:36259/
[rospy.internal][WARNING] 2019-06-25 13:34:23,742: Unknown error initiating TCP/IP socket to dc5b429f784e:54235 (http://dc5b429f784e:36259/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][ERROR] 2019-06-25 13:34:23,742: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 729, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.topics][ERROR] 2019-06-25 13:34:23,744: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2019-06-25 13:34:23,744: topic[/tf] removing connection to http://dc5b429f784e:38229/
[rospy.internal][WARNING] 2019-06-25 13:34:23,745: Unknown error initiating TCP/IP socket to dc5b429f784e:46219 (http://dc5b429f784e:38229/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][WARNING] 2019-06-25 13:34:23,746: Unknown error initiating TCP/IP socket to dc5b429f784e:41267 (http://dc5b429f784e:46007/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2019-06-25 13:34:23,745: topic[/tf] removing connection to http://dc5b429f784e:46007/
[rospy.impl.masterslave][INFO] 2019-06-25 13:34:23,747: atexit
