[rospy.client][INFO] 2019-06-25 15:16:48,313: init_node, name[/spawn_pr2_model], pid[19305]
[xmlrpc][INFO] 2019-06-25 15:16:48,321: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-25 15:16:48,322: Started XML-RPC server [http://dc5b429f784e:41325/]
[rospy.impl.masterslave][INFO] 2019-06-25 15:16:48,323: _ready: http://dc5b429f784e:41325/
[rospy.init][INFO] 2019-06-25 15:16:48,323: ROS Slave URI: [http://dc5b429f784e:41325/]
[xmlrpc][INFO] 2019-06-25 15:16:48,324: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 15:16:48,325: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-06-25 15:16:48,424: registered with master
[rospy.rosout][INFO] 2019-06-25 15:16:48,425: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 15:16:48,429: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 15:16:48,433: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 15:16:48,439: connected to core topic /clock
[rosout][INFO] 2019-06-25 15:16:48,448: Loading model XML from ros parameter
[rosout][INFO] 2019-06-25 15:16:48,470: Waiting for service /gazebo/spawn_urdf_model
[rosout][INFO] 2019-06-25 15:16:48,491: Calling service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2019-06-25 15:16:48,502: topic[/clock] adding connection to [http://dc5b429f784e:41589/], count 0
[rospy.internal][INFO] 2019-06-25 15:16:48,711: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2019-06-25 15:16:51,170: Spawn status: SpawnModel: Successfully spawned entity
[rospy.core][INFO] 2019-06-25 15:16:51,190: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-25 15:16:51,201: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 15:16:51,201: topic[/clock] removing connection to http://dc5b429f784e:41589/
[rospy.topics][ERROR] 2019-06-25 15:16:51,202: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2019-06-25 15:16:51,202: atexit
[rospy.internal][WARNING] 2019-06-25 15:16:51,203: Unknown error initiating TCP/IP socket to dc5b429f784e:36451 (http://dc5b429f784e:41589/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

