[rospy.client][INFO] 2019-06-25 21:59:23,312: init_node, name[/joint_state_publisher], pid[19449]
[xmlrpc][INFO] 2019-06-25 21:59:23,314: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2019-06-25 21:59:23,316: ROS Slave URI: [http://dc5b429f784e:38771/]
[xmlrpc][INFO] 2019-06-25 21:59:23,316: Started XML-RPC server [http://dc5b429f784e:38771/]
[rospy.impl.masterslave][INFO] 2019-06-25 21:59:23,316: _ready: http://dc5b429f784e:38771/
[xmlrpc][INFO] 2019-06-25 21:59:23,317: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-25 21:59:23,319: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-06-25 21:59:23,416: registered with master
[rospy.rosout][INFO] 2019-06-25 21:59:23,417: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-25 21:59:23,423: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-25 21:59:23,426: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-25 21:59:23,432: connected to core topic /clock
[rospy.internal][INFO] 2019-06-25 21:59:23,442: topic[/clock] adding connection to [http://dc5b429f784e:41861/], count 0
[rospy.internal][INFO] 2019-06-25 21:59:23,635: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-06-25 21:59:23,844: topic[/joint_states] adding connection to [/robot_state_publisher], count 0
[rospy.internal][ERROR] 2019-06-25 22:04:50,506: Unable to initiate TCP/IP socket to dc5b429f784e:47989 (http://dc5b429f784e:41861/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 47989 to [172.17.0.2:46576 on socket 16]] [/joint_state_publisher].

[rospy.core][INFO] 2019-06-25 22:04:50,985: signal_shutdown [signal-2]
[rospy.internal][INFO] 2019-06-25 22:04:50,992: topic[/joint_states] removing connection to /robot_state_publisher
[rospy.internal][INFO] 2019-06-25 22:04:50,992: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-25 22:04:50,992: topic[/clock] removing connection to http://dc5b429f784e:41861/
[rospy.impl.masterslave][INFO] 2019-06-25 22:04:50,992: signal-2
[rospy.core][INFO] 2019-06-25 22:04:51,271: signal_shutdown [atexit]
